version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    #restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx/
    networks:
      - backend
      - public
    depends_on:
      - php
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 7s
      timeout: 7s
      retries: 3

  php:
    image: dopanel/php-postgres-laravel-cron-logrotate
    #restart: always
    expose:
      - "9000"
    volumes:
      - ./:/code
    networks:
      - backend
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "test $(netstat -an | grep :9000 | wc -l) -gt 0"]
      interval: 7s
      timeout: 7s
      retries: 3

  postgres:
    image: postgres:12-alpine
    #restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 7s
      timeout: 7s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    #restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=passwordHere2023
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DISABLE_POSTFIX=true
    ports:
      - "5050:5050"
    networks:
      - backend
      - public

  redis:
    image: redis:alpine
    #restart: always
    command: redis-server --appendonly yes --requirepass passwordHere2023
    volumes:
      - ./docker/volumes/redis:/data
    expose:
      - "6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 7s
      timeout: 7s
      retries: 3

networks:

  public:
    driver: bridge

  backend:
    driver: bridge
