services:

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./docker/configs/nginx:/etc/nginx/conf.d #Use Your Nginx Config, this is just a example
    depends_on:
      - php
    healthcheck:
      test: ["CMD-SHELL", "curl -so /dev/null http://localhost/ || exit 1"]
      interval: 7s
      timeout: 7s
      retries: 3

  php:
    image: dopanel/php-postgres-cron-logrotate-laravel-optimized:8.3-fpm-alpine
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./:/code
    healthcheck:
      test: ["CMD-SHELL", "test $(netstat -an | grep :9000 | wc -l) -gt 0"]
      interval: 7s
      timeout: 7s
      retries: 3